repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-ast
      - id: double-quote-string-fixer
      - id: detect-private-key
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-json

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.80.0"
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        exclude: modules
